# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65vent.proto\x12\x05\x45vent\"\x18\n\x06Record\x12\x0e\n\x06result\x18\x01 \x01(\t\"\x16\n\x05query\x12\r\n\x05query\x18\x01 \x01(\t2>\n\x0c\x45ventService\x12.\n\rGetAllRecords\x12\x0c.Event.query\x1a\r.Event.Record\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'event_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RECORD._serialized_start=22
  _RECORD._serialized_end=46
  _QUERY._serialized_start=48
  _QUERY._serialized_end=70
  _EVENTSERVICE._serialized_start=72
  _EVENTSERVICE._serialized_end=134
# @@protoc_insertion_point(module_scope)
